= Default Interceptors
Michael Nygard
2016-08-09
:jbake-type: page
:toc: macro
:icons: font
:section: reference


== Description

If your <<service-map.adoc#,Service Map>> does not include the key
`:io.pedestal.http/interceptors`, then Pedestal will create a vector of
default interceptors for you.

The default interceptors are added to your service map when you call
either
link:../api/pedestal.service/io.pedestal.http.html#var-create-servlet[`create-servlet`]
or
link:../api/pedestal.service/io.pedestal.http.html#var-create-server[`create-server`].

This document explains which interceptors are added under different
conditions. Each interceptor has it's own documentation that describes
its specific behavior.

Some of the default interceptors are conditional. Pedestal adds them
when other parts of the service map indicate a need for an
interceptor. These will be noted below.

These are presented in the order that they appear in the interceptor
vector. That means their `enter` functions will be called in the order
they appear in this document, and their `leave` functions are called
in reverse order.

=== link:../api/pedestal.service/io.pedestal.http.html#var-log-request[`log-request`]

Always added. Logs each request at `info` level. See link:logging[Logging]
to configure loggers and logging levels.

=== link:../api/pedestal.service/io.pedestal.http.cors.html#var-allow-origin[`allow-origin`]

Added when the service map has a value for `:io.pedestal.http/allowed-origins`.

=== link:../api/pedestal.service/io.pedestal.http.html#var-not-found-interceptor[`not-found`]

Always added. However, if the service map includes a value for
`:io.pedestal.http/not-found-interceptor`, then that interceptor will
be used in this position instead of the built-in.

=== link:../api/pedestal.service/io.pedestal.http.ring-middlewares.html#var-session[`session`]

Added when the service map has a value for
`:io.pedestal.http/enable-session` or `:io.pedestal.http/enable-csrf`.

=== link:../api/pedestal.service/io.pedestal.http.csrf.html#var-anti-forgery[`anti-forgery`]

Added when the service map includes a value for `:io.pedestal.http/enable-csrf`.

=== link:../api/pedestal.service/io.pedestal.http.ring-middlewares.html#var-content-type[`content-type`]

Always added.

=== link:../api/pedestal.route/io.pedestal.http.route.html#var-query-params[`query-params`]

Always added

=== link:../api/pedestal.route/io.pedestal.http.route.html#var-method-param[`method-param`]

Always added

=== link:../api/pedestal.service/io.pedestal.http.ring-middlewares.html#var-resource[`resource`]

Added when the service map has a value for `:io.pedestal.http/resource-path`.

=== link:../api/pedestal.service/io.pedestal.http.ring-middlewares.html#var-file[`file`]

Added when the service map has a value for `:io.pedestal.http/file-path`.

=== link:../api/pedestal.service/io.pedestal.http.secure-headers.html#var-secure-headers[`secure-headers`]

Added when the service map has a non-nil value for
`:io.pedestal.http/secure-headers` or when the service map does not
include the key `:io.pedestal.http/secure-headers` at all.

=== link:../api/pedestal.route/io.pedestal.http.route.html#var-router[`router`]

Always added.
