= Handlers
Michael Nygard
2016-08-26
:jbake-type: page
:toc: macro
:icons: font
:section: reference

ifdef::env-github,env-browser[:outfilessuffix: .adoc]

== Handler functions

A _handler_ is a function that receives a link:request-map[Request
Map] and returns a link:response-map[Response Map].

== Example

[source,clojure]
----
(defn reply-hello [request]
  {:status 200 :body (str "Hello, " (get-in request [:params :name]))})
----

== Additional Information

Because the handler exchanges a request for a response, it will be the
last interceptor to execute.

Handler functions are wrapped into Interceptors when expanding
routes. This happens because the
link:../api/io.pedestal.interceptor.html#var-IntoInterceptor[`IntoInterceptor`]
protocol is extended to functions. The handler function is wrapped
into the interceptor's `:enter` function.

Handlers do not have access to the full execution context (the link:context-map[context map]), so they
cannot terminate execution or enqueue additional interceptors.

If a handler throws an exception, Pedestal catches it and begins error
handling. See link:error-handling[Error Handling] for details.

== See Also

* link:interceptors[Interceptors]
