= Important Protocols
Michael Nygard
2016-10-18
:jbake-type: page
:toc: macro
:icons: font
:section: reference

ifdef::env-github,env-browser[:outfilessuffix: .adoc]

The major parts of Pedestal are isolated via Clojure protocols. The
protocols are for internal structure and external extension. This
reference identifies the most important protocols in Pedestal's
structure and how you might use them in an application.

== Interceptor Protocols

=== link:../api/pedestal.interceptor/io.pedestal.interceptor.html#var-IntoInterceptor[`IntoInterceptor`]

`IntoInterceptor` allows pretty much anything to become an interceptor
when needed.

Routers use this when building routes: anything that satisfies
`IntoInterceptor` is legal to use in the interceptor vector of a
route.

Pedestal extends `IntoInterceptor` onto a variety of Clojure and Java
types. See the link:interceptors#_intointerceptor[interceptors
reference] for details of their behaviors.

== Routing Protocols

These protocols break up the lifecycle of routes and allow both
extension points and alternative strategies in several places.

To give you an idea what that means, there are three built-in route
definition syntaxes: table, terse, and verbose. There are three built
in routing algorithms: linear-search, prefix-tree, and map-tree. An
application can use any syntax with any algorithm. Or, an application
can create a new syntax while using a built-in algorithm. Or, an
application could use a built-in syntax with a new algorithm!

=== link:../api/pedestal.route/io.pedestal.http.route.router.html#var-Router[`Router`]

This protocol defines one function: `find-route`. It takes the router
itself and a link:request-map[request map]. It must return the
route map for the route that it matched.

An instance of `Router` is returned by the router constructor
identified by the application's link:service-map[service map] in the key `:io.pedestal.http/router`.

|===
| Key            | Constructor
| :linear-search | link:../api/pedestal.route/io.pedestal.http.route.linear-search.html#var-router[`linear-search/router`]
| :prefix-tree   | link:../api/pedestal.route/io.pedestal.http.route.prefix-tree.html#var-router[`prefix-tree/router`]
| :map-tree      | link:../api/pedestal.route/io.pedestal.http.route.map-tree.html#var-map-tree[`map-tree/router`]
| application-supplied function | The function itself, called with sequence of routes as returned by `RouterSpecification`'s `router-spec` function.
|===

=== link:../api/pedestal.route/io.pedestal.http.route.html#var-RouterSpecification[`RouterSpecification`]

`RouterSpecification` creates a routing interceptor from some
definition of routes and a constructor. This is the final step in the
process of turning route definitions into the executable router.

Whatever is returned from the
link:../api/pedestal.route/io.pedestal.http.route.html#var-router-spec[`router-spec`]
function of the protocol must be an interceptor. It must accept a
link:context-map[context map] and enqueue
link:interceptors[interceptors] based on whatever criteria is chooses.

=== link:../api/pedestal.route/io.pedestal.http.route.html#var-ExpandableRoutes[`ExpandableRoutes`]

`ExpandableRoutes` abstracts over anything that
link:../api/pedestal.route/io.pedestal.http.route.html#var-expand-routes[`expand-routes`]
knows how to use.

Pedestal extends `ExpandableRoutes` as follows:

|===
| Type | Behavior
| `clojure.lang.APersistentVector` | Interpret the vector as link:terse-syntax[terse routing syntax].
| `clojure.lang.APersistentMap`    | Interpret the map as link:verbose-syntax[verbose routing syntax].
| `clojure.lang.APersistentSet`    | Interpret the set as link:table-syntax[table routing syntax].
|===

Since the call to `expand-routes` comes from application code, it
would be rare for an application to need to extend `ExpandableRoutes`.

== Servlet Protocols

These protocols only apply when using the link:servlet-interceptor[`servlet interceptor`].

=== link:../api/pedestal.service/io.pedestal.http.impl.servlet-interceptor.html#var-WritableBody[`WritableBody`]

This protocol applies to anything that can be in the `:body` key of a
link:response-map[response map]. The two functions in the protocol
tell Pedestal what content type the body implies, and how to serialize
the body to an output stream.

Pedestal extends this protocol to several Java and Clojure types to produce the behavior detailed in link:response-bodies[Response Bodies].

Applications should not assume any output stream type more specific
than `java.io.OutputStream`.

=== link:../api/pedestal.service/io.pedestal.http.impl.servlet-interceptor.html#var-WritableBodyAsync[`WritableBodyAsync`]

This protocol is a more specific version of `WritableBody`. If the
value in the `:body` key of a link:response-map[response map]
satisfies `WritableBodyAsync`, then Pedestal treats it as a streaming
result. See link:streaming[Streaming] for full details.

It would be rare for an application to extend this protocol. Most of
the time, an application would be better off providing an NIO channel
or a core.async channel in the response body.
