site:
  title: Pedestal
  start_page: pedestal::index.adoc
content:
  sources:
  - url: https://github.com/pedestal/pedestal.git
    branches: [master, '*-maint']
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-overrides
asciidoc:
  extensions:
    - lib/pedestal-macros.js
    - asciidoctor-kroki
  attributes:
    # Convert diagrams to SVG on the server
    kroki-fetch-diagram: true
    # Kroki runs locally via `docker compose up -d`
    kroki-server-url: http://localhost:8005
antora:
  extensions:
    - '@antora/lunr-extension'
