= Cookbook
Cognitect
2020-01-31
:jbake-type: page
:toc: macro
:icons: font
:section: cookbook

== How to test your servlet-based service

Use the link:../api/io.pedestal.test.html#var-response-for[`response-for`]
test helper to facilitate testing servlet-based services. It is
recommended to create a `url-for` test helper in order to construct
test requests, particularly when query or path parameters are
involved.

Reference: link:../reference/unit-testing[Unit Testing]

[[cookbook-listing]]
[source,clojure]
----
include::test/how_to_test/service_test.clj[]
----

== How to Handle Errors

Add an `:error` implementation to your interceptor(s) or create a
purpose-built, error handling interceptor.  If you can't handle the
exception in your error handler, re-attach it to the context
using the `io.pedestal.interceptor.chain/error` key so that other
interceptors have an opportunity to handle it.

Reference: link:../reference/error-handling[Error Handling]

[[cookbook-listing]]
[source,clojure]
----
include::src/error_handling/service.clj[]
----

== How to serve static resources

Add the `:io.pedestal.http/resource-path` key to the service map and
set your project's _resource_ path to the root resource directory.

If your _resources_ directory is `resources` then
`:io.pedestal.http/resource-path "/public"` will instruct Pedestal to
look for static content in the `resources/public` directory.  Thus,
`http://localhost:8080/foo.txt` would serve
`resources/public/foo.txt`.

If a resource is not found and no route matches the url, then a `404`
is returned.
              
Reference: link:../reference/service-map[Service Map]

[[cookbook-listing]]
[source,clojure]
----
include::src/static_resource/service.clj[tags=service]
----

== How to specify custom verbs

You can specify custom verbs when creating routes. This can be done with
the Table Routes syntax, for example, by including a map with the key `:verbs`
in your route definition. The value of `:verbs` is a `set` containg the verbs you
wish to support. This set will replace the default set of verbs supported by
Pedestal.

Reference: link:../reference/table-syntax#_http_verb[Table Syntax Http Verb]

[[cookbook-listing]]
[source,clojure]
----
include::src/verb_neutral_routes/service.clj[tags=routes]
----

== How to override request logging

The `log-request` is always added as the first of the link:../reference/default-interceptors[default interceptors].
This will log requests as they come in (using `io.pedestal.log`), according to how your logging infrastructure
is configured.

The default logger will output something like:

----
INFO io.pedestal.log {:msg "GET /status", :line 80}
----

To disable the log entirely, set the logger to `nil` in the link:../reference/service-map[service map]:

[source,clojure]
----
(-> {::http/request-logger nil}
    http/default-interceptors)
----

=== Custom log format

To modify the log message, for example, to log request timing, you can use a custom interceptor.
In this example, we use `io.pedestal.log`, but you can freely use
link:https://github.com/clojure/tools.logging[`org.clojure/tools.logging`] or
any other logging mechanism.

[[cookbook-listing]]
[source,clojure]
----
include::src/logging/service.clj[]
----

This will output something like:

----
INFO logging.service {:method "GET", :msg "request completed", :line "24", :status 200, :uri "/status", :response-time 5}
----

This can obviously be extended to log unique request ids, user details,
`:json-params` from the body or anything else as required.
