= Server Sent Events
Larry Christensen
2018-04-15
:jbake-type: page
:toc: macro
:icons: font
:section: guides

toc::[]

_by {author}_, _{revdate}_

== Welcome

Server-sent events (SSE) make it possible to stream events to a client application.
They are appropriate when you only need a unidirectional flow of events from the
server to the client (if you need a bidirectional connection, then WebSockets are
a better choice).

== What You Will Learn

After reading this guide, you will be able to:

- Configure Pedestal to accept SSE connections.
- Send events from Pedestal over the connection using +core.async+.
- Connect to the server-sent event stream from a JavaScript client.

== Guide Assumptions

This guide is for intermediate users who have worked through some
sample applications or the first few link:hello-world[Hello World]
guides. In particular you should know how to run a build, start a
REPL, and start and stop your server.

You do not need to know any other Clojure web frameworks, but if you
do, you may find some of the comparisons useful. If not, that's OK --
just skip those sections.

== Getting Help if You're Stuck

If you get stuck at any point in this guide, please create an
https://github.com/pedestal/docs/issues[issue] or hop
over to the
https://groups.google.com/forum/#!forum/pedestal-users[mailing list]
and raise your questions there. You can often find help in the "#pedestal"
channel of the https://clojurians.slack.com[Clojurians Slack team.]

== Where We Are Going

We'll be creating a new Pedestal service project, adding a simple route to stream a counter using server-sent events, and adding a simple HTML page that uses a JavaScript https://developer.mozilla.org/en-US/docs/Web/API/EventSource[EventSource] to open a connection to the stream.

== Before We Begin

This guide will use http://leiningen.org/[Leiningen] to generate and
build a template project. If you haven't already installed it, please
take a few minutes to set it up.

== Generate Our New Project

----
$ lein new pedestal-service server-sent-events
Generating a pedestal-service application called server-sent-events.
$ cd server-sent-events
----

== Add Hiccup

We will be using Hiccup to generate our index page, so we will need to add the
dependency in our project.clj.

[source,clojure]
.project.clj
----
include::server-sent-events/project.clj[tags=add-hiccup]
----

== Clean Up

Here's the service.clj file generated for us:

[source,clojure]
.src/server_sent_events/service.clj
----
include::server-sent-events/src/server_sent_events/service.clj[tags=original-service]
----

Let's simplify things by commenting out the 'Terse/Vector-based routes' section and removing unnecessary code.

[source,clojure]
.src/server_sent_events/service.clj
----
include::server-sent-events/src/server_sent_events/service.clj[tags=cleaned-up]
----

== Server-Sent Event Route

Now let's add our server-sent event route. First Lets require SSE and core.async.

[source,clojure]
.src/server_sent_events/service.clj
----
include::server-sent-events/src/server_sent_events/service.clj[tags=require-sse]
----

Now we'll add our counter route. We create the +/counter+ route by calling +sse/start-event-stream+ and passing in our +stream-ready+ handler. This creates an interceptor that will handle setting up the connection and call the +stream-ready+ handler. A +stream-ready+ handler receives a +core.async+ event channel and SSE context as parameters. The +stream-ready+ handler *must* send at least one event in order to properly initialize the stream. If it doesn't, the client will think the stream is broken and keep reconnecting.

You send events on the channel using regular core.async (such as +async/>!!+)
functions and terminate the connection by calling +async/close!+ on the channel.
Here our event consists the +:name+ and +:data+ keys, but could also contain an
+:id+ for the event. Note that the events that you send on the channel can
happen any time later. They don't all have to be created and sent in the
+stream-ready+ handler.

[source,clojure]
.src/server_sent_events/service.clj
----
include::server-sent-events/src/server_sent_events/service.clj[tags=counter-route]
----

Now let's start up our server.

----
$ lein run
...
Creating your server...
...
INFO  org.eclipse.jetty.server.Server - Started @4434ms
----

We can check out our event stream in another terminal using +curl+.

----
$ curl http://localhost:8080/counter
event: counter
data: 0

event: counter
data: 1

event: counter
data: 2

event: counter
data: 3

event: counter
data: 4

event: counter
data: 5

event: counter
data: 6

event: counter
data: 7

event: counter
data: 8

event: counter
data: 9

----

SSE data will always be received as a string. If you want to send JSON (or any
other data format), it's up to the sender to encode it and the receiver to
decode it accordingly. This agreement must be arranged out-of-band.

Also, it's important to note that _none of the Pedestal interceptors are invoked
when sending SSE events_. The interceptors are used for the initial connection
request from the client, but not on the events themselves.

Now let's stop our server (+CTRL-C+) and update our index route to return an
HTML page that connects to our counter route. Since we are adding inline JS
we'll also update our service configuration not to include secure headers, which
include 'unsafe-inline' by default (this is an example, not production code
after all).

[source,clojure]
.src/server_sent_events/service.clj
----
include::server-sent-events/src/server_sent_events/service.clj[tags=html-home]
----

Now we should be able to restart our server and navigate to http://localhost:8080 and watch our counter increment.

== Wrapping Up

We've covered a minimal setup for server-sent event configuration and usage and
demonstrated how to receive events from JavaScript.

This guide was based on the examples in the 
link:https://github.com/pedestal/samples/tree/master/server-sent-events[server-sent-event sample project]
and the
link:../reference/server-sent-events[Server-Send Events Reference].
Please see those references for further information.
